version: '3.8'
name: 'nestjs-user-auth-prod'
services:
  api:
    container_name: nestjs_api_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres_db_prod
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
