name: 'ai-workspace'
services:
  api:
    container_name: backend_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: database_prod
    image: postgres:16
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
