name: 'ai-workspace-dev'
services:
  backend:
    container_name: backend_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    command: pnpm run start:dev
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: database_dev
    image: postgres:16 
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
          - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
